In [8]:
#Cargar base desde drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [8]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
df = pd.read_csv("R2023.csv", delimiter=';')
df1 = pd.read_csv("R2022.csv", delimiter=';')
df2 = pd.read_csv("R2021.csv", delimiter=';')
df3 = pd.read_csv("R2020.csv", delimiter=';')
df_prueba= pd.read_csv("2024.csv", delimiter=';')

C:\Users\benja\AppData\Local\Temp\ipykernel_16984\8307221.py:1: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("R2023.csv", delimiter=';')
C:\Users\benja\AppData\Local\Temp\ipykernel_16984\8307221.py:2: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  df1 = pd.read_csv("R2022.csv", delimiter=';')
C:\Users\benja\AppData\Local\Temp\ipykernel_16984\8307221.py:3: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  df2 = pd.read_csv("R2021.csv", delimiter=';')
C:\Users\benja\AppData\Local\Temp\ipykernel_16984\8307221.py:4: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  df3 = pd.read_csv("R2020.csv", delimiter=';')
C:\Users\benja\AppData\Local\Temp\ipykernel_16984\8307221.py:5: DtypeWarning: Columns (17,22,23,24,25,26) have mixed types. Specify dtype option on import or set low_memory=False.
  df_prueba= pd.read_csv("2024.csv", delimiter=';')

In [4]:
#df_merged = pd.concat([df, df1, df2, df3], axis=0, ignore_index=True)

In [11]:
df_prueba

,MRUN,ANYO_PROCESO,COD_SEXO,FECHA_NACIMIENTO,RBD,CODIGO_ENS,LOCAL_EDUCACIONAL,UNIDAD_EDUCATIVA,NOMBRE_UNIDAD_EDUC,RAMA_EDUCACIONAL,...,PRUEBA_INV_CQUI,FORMA_INV_CQUI,CORRECTAS_INV_CQUI,ERRADAS_INV_CQUI,OMITIDAS_INV_CQUI,PRUEBA_INV_CTP,FORMA_INV_CTP,CORRECTAS_INV_CTP,ERRADAS_INV_CTP,OMITIDAS_INV_CTP
0,6160406,2024,2,196401,9077,310,924,1,COMPLEJO EDUC.MUN. BRIGIDA WALKER.,H1,...,Ciencias Química.,0,0,0,0,Ciencias Técnico Profesional.,0,0,0,0
1,7259152,2024,2,196706,24474,360,971,4,FUNDACION DUOC,H2,...,Ciencias Química.,0,0,0,0,Ciencias Técnico Profesional.,0,0,0,0
2,9774983,2024,1,194201,14492,363,2323,1,CENTRO EDUCACIÓN ADULTOS PEDRO DE VALDIVIA,H2,...,Ciencias Química.,0,0,0,0,Ciencias Técnico Profesional.,0,0,0,0
3,1085674,2024,2,194409,,,,,,,...,Ciencias Química.,0,0,0,0,Ciencias Técnico Profesional.,0,0,0,0
4,18615634,2024,2,194502,4553,300,1647,7,LICEO DE NIÑAS,H1,...,Ciencias Química.,0,0,0,0,Ciencias Técnico Profesional.,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
309347,26247247,2024,1,202203,578,510,160,5,LICEO BICENTENARIO DE EXCELENCIA IGNACIO CARRE...,T2,...,Ciencias Química.,0,0,0,0,Ciencias Técnico Profesional.,0,0,0,0
309348,26366551,2024,2,202203,12117,410,912,3,COMPLEJO EDUCACIONAL J. MIGUEL CARRERA,T1,...,Ciencias Química.,0,0,0,0,Ciencias Técnico Profesional.,0,0,0,0
309349,26457224,2024,2,202203,11139,410,158,3,LICEO FERNANDO BINVIGNAT MARIN,T1,...,Ciencias Química.,0,0,0,0,Ciencias Técnico Profesional.,0,0,0,0
309350,26456378,2024,2,202203,25969,310,3243,1,COLEGIO TERCER MILENIO,H1,...,Ciencias Química.,0,0,0,0,Ciencias Técnico Profesional.,0,0,0,0
309351,27583289,2024,2,202302,,,,,,H4,...,Ciencias Química.,0,0,0,0,Ciencias Técnico Profesional.,0,0,0,0

In [3]:
# Supongo que df1, df2, df3 también son DataFrames que contienen la columna 'MRUN'
#df_prueba = df_prueba.to_frame()
#df_prueba = df_prueba['MRUN']

columnas2020 = []
columnas2021 = []
columnas2022 = []
columnas2023 = []

for each in df_prueba['MRUN']:
    # Para df
    row = df[df['MRUN'] == int(each)]
    if not row.empty:
        columnas2023.append([row['GEN_ALU'].values[0], row['EDAD_ALU'].values[0], row['COD_COM_ALU'].values[0], row['PROM_GRAL'].values[0], row['ASISTENCIA'].values[0], row['COD_JOR'].values[0], row['COD_COM_RBD'].values[0]])

    # Para df1
    row1 = df1[df1['MRUN'] == int(each)]
    if not row1.empty:
        columnas2022.append([row1['PROM_GRAL'].values[0], row1['ASISTENCIA'].values[0]])

    # Para df2
    row2 = df2[df2['MRUN'] == int(each)]
    if not row2.empty:
        columnas2021.append([row2['PROM_GRAL'].values[0], row2['ASISTENCIA'].values[0]])

    # Para df3
    row3 = df3[df3['MRUN'] == int(each)]
    if not row3.empty:
        columnas2020.append([row3['PROM_GRAL'].values[0], row3['ASISTENCIA'].values[0]])

In [6]:
MRUN = pd.DataFrame(df_prueba['MRUN'])


df2020 = pd.DataFrame(columnas2020, columns=[ 'PROM_GRAL2020', 'ASISTENCIA2020'])
df2021 = pd.DataFrame(columnas2021, columns=[ 'PROM_GRAL2021', 'ASISTENCIA2021'])
df2022 = pd.DataFrame(columnas2022, columns=[ 'PROM_GRAL2022', 'ASISTENCIA2022'])
df2023 = pd.DataFrame(columnas2023, columns=['GEN_ALU2023', 'EDAD_ALU', 'COD_COM_ALU2023','PROM_GRAL2023', 'ASISTENCIA2023', 'COD_JOR', 'COD_COM_RBD'])

MRUN = pd.concat([MRUN.reset_index(drop=True), df2020, df2021, df2022, df2023], axis=1)

In [9]:
MRUN['MismaCom'] = np.where(MRUN['COD_COM_RBD'] == MRUN['COD_COM_ALU2023'], 1, 0)

In [10]:
MRUN.to_csv("rendimiento.csv",index=False)